services:
  battle-db:
    image: postgres:18
    container_name: ${DEPLOYMENT_PREFIX:-main}-battle-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      -  ${ABS_PROJECT_DIR}/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    networks:
      - battle-internal

  battle-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${DEPLOYMENT_PREFIX:-main}-battle-backend
    restart: unless-stopped
    depends_on:
      battle-db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DEPLOYMENT_PREFIX:-main}-battle-db:5432/${POSTGRES_DB}"
      SECRET_KEY: ${SECRET_KEY}
      CORS_ORIGINS: ${CORS_ORIGINS}
      JWT_ALGORITHM: ${JWT_ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-}
    expose:
      - "8000"
    networks:
      - battle-internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${DEPLOYMENT_PREFIX:-main}-battle-api.rule=Host(`${DEPLOYMENT_PREFIX:-main}-app.battle.wopee.io`) && PathPrefix(`/auth`, `/items`, `/health`, `/docs`, `/openapi.json`)"
      - "traefik.http.routers.${DEPLOYMENT_PREFIX:-main}-battle-api.entrypoints=websecure"
      - "traefik.http.routers.${DEPLOYMENT_PREFIX:-main}-battle-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.${DEPLOYMENT_PREFIX:-main}-battle-api.loadbalancer.server.port=8000"

  battle-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ${DEPLOYMENT_PREFIX:-main}-battle-frontend
    restart: unless-stopped
    depends_on:
      - battle-backend
    environment:
      BACKEND_URL: ${DEPLOYMENT_PREFIX:-main}-battle-backend:8000
    expose:
      - "3000"
    networks:
      - battle-internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${DEPLOYMENT_PREFIX:-main}-battle-app.rule=Host(`${DEPLOYMENT_PREFIX:-main}-app.battle.wopee.io`)"
      - "traefik.http.routers.${DEPLOYMENT_PREFIX:-main}-battle-app.entrypoints=websecure"
      - "traefik.http.routers.${DEPLOYMENT_PREFIX:-main}-battle-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.${DEPLOYMENT_PREFIX:-main}-battle-app.loadbalancer.server.port=3000"


networks:
  battle-internal:
    driver: bridge
  proxy:
    external: true
